app:
  name: "Agentic SF Dev"
  env: "sandbox"
  base_url: "http://localhost:8000"

llm:
  provider: "openai"        # openai|gemini
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 4096

memory:
  store: "sqlite"
  vector_dim: 1536
  per_session: true

mcp:
  salesforce:
    command: "/bin/bash"
    args: [
      "-lc",
      "cd '/Users/niteshsinwar/Desktop/My Stuff/My Projects/Salesforce MCP Server/sfmcp' && source venv/bin/activate && python -m app.main --mcp-stdio"
    ]
  github:
    command: "docker"
    args: [
      "run",
      "-i",
      "--rm",
      "-e",
      "GITHUB_PERSONAL_ACCESS_TOKEN",
      "ghcr.io/github/github-mcp-server"
    ]
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_TOKEN}"
  playwright:
    command: "npx"
    args: ["@playwright/mcp@latest"]

github:
  repo: "your-org/your-repo"
  default_branch: "main"

paths:
  workspace: "./workspace"
  testplans: "./workspace/testplans"
  ui_json: "./workspace/ui"
  logs: "./logs/sessions"
